# Generated by Django 2.0.7 on 2021-05-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='global',
            name='ShowFromCache',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='IsCached',
            field=models.BigIntegerField(default=0),
        ),
    ]
